### PR TITLE
Clarify Weaviate instructions

### PR DESCRIPTION
**Pull request by dandv**
Submitting a few changes after seeing folks getting tripped by the docs during the ChatGPT Plugins Hackathon at SHACK15 (Weaviate was one of the sponsors).

1. Rename the env var `WEAVIATE_INDEX` to `WEAVIATE_CLASS`, per Weaviate terminology
2. Clarify that the `BEARER_TOKEN` is not the Weaviate one
3. Inline the 443 port number for WCS

### CODE REVIEW

**Comment by gmverdon** [comment]
Please approve this @openai

**Review by isafulf — COMMENTED** [review]
LGTM -- can you just resolve conflicts first? Thanks!

**Comment by dandv** [comment]
@isafulf done!

**Review by isafulf — APPROVED** [review]
lgtm!

**Comment by davidgovea** [comment]
Looks like the `WEAVIATE_INDEX` rename missed one instance. Guessing due to merge conflicts.

Quick fix PR here:
* #210

**Pull request merged**
