### PR TITLE
Add Postgres Datastore

### PR DESCRIPTION
**Pull request by raoufchebri**
Hi there 👋 ,

I'm excited to open this PR to add support for using Postgres with the `pgvector` extension in ChatGPT plugins. This provides developers with a popular and robust database option to work with. The PR includes:

- `PostgresDatastore`
- Query to create `documents` table to store embeddings
- Query to create `pgvector` and `uuid-ossp` extensions
- Query to calculate similarity using `pgvector` extension
- Updated README.md with a list of [hosted providers](https://github.com/pgvector/pgvector/issues/54).

The provider is simple to use; all you need to provide is a `DATABASE_URL`.

I look forward to your feedback and am happy to make any necessary changes. Let's keep making the ChatGPT plugin ecosystem even better!

### CODE REVIEW

**Comment by mmmaia** [comment]
There are two other PRs addressing `pgvector` support:

  - https://github.com/openai/chatgpt-retrieval-plugin/pull/45
  - https://github.com/openai/chatgpt-retrieval-plugin/pull/53

**Comment by raoufchebri** [comment]
I agree we need one Postgres implementation but I'm not sure about calling the datastore  `pgvector`.

Postgres users wouldn't know it's Postgres.

This implementation requires just a connection string, which makes it simple to get started.

**Comment by mmmaia** [comment]
> I agree we need one Postgres implementation but I'm not sure about calling the datastore `pgvector`.

Agreed! I was not sure about it either because pgvector is not very known yet. I like your wording on the `README`:

> You can use Postgres as a vector database with the [pgvector](https://github.com/pgvector/pgvector) extension.

On the technical side, do have any hard opinions about using just `psycopg2` vs `sqlalchemy`?

**Comment by raoufchebri** [comment]
> On the technical side, do have any hard opinions about using just `psycopg2` vs `sqlalchemy`?
No strong opinion there.

**Review by DSosnovsky — APPROVED** [review]
Nice!

**Review by DSosnovsky — APPROVED** [review]

**Comment by raoufchebri** [comment]
Hi @isafulf! 👋 
Please, let me know if there is anything I can do to merge this PR! Thanks 🙏

**Comment by joyanujoy** [comment]
This is very nice as there is no dependency on ORM etc. Thank you 🙏 

A few comments from me(I'm not 100% sure about these, apologies if I got it wrong)

1. It appears `MERGE INTO` is only available from Postgres version 15+
2. I had to remove sslmode in the connection to make it work with local Postgres.app `self.conn = connect(DATABASE_URL, sslmode='require')`
3. When I tried upserting an existing doc id, the plugin wiped out many records. Is the below statement in "delete" method correct? `if filter.document_id:
                    where_conditions.append(f"document_id <= '{filter.document_id}'")` . Seems to work okay if I change `<=` to `=`
4. I'm not at all sure about this point. I was getting incorrect document matches from cosine similarity. Below change in the query method appears to give better matches.
Change `(embedding <=> '{embedding}') * -1 AS similarity` to `1 - (embedding <=> '{embedding}') AS similarity`
Change `ORDER BY similarity` to `f"ORDER BY embedding <=> '{embedding}'`

**Review by ankit-gautam23 — COMMENTED** [review]
Is the version you added is compatible with the code we had earlier?

**Comment by kk-src** [comment]
Hi @raoufchebri - please let me know how I can help on any further changes needed for PR. 
Hi @isafulf - wondering if you got a chance to look at the PR.

**Comment by isafulf** [comment]
https://github.com/openai/chatgpt-retrieval-plugin/pull/53

**Pull request closed without merging**
