### PR TITLE
Added Elasticsearch datastore

### LINKED ISSUE #52: Support for Elasticsearch data store
It would be great to support [Elasticsearch](https://www.elastic.co/partners/microsoft-azure) as a data store, to use the embedding similarity search functionality and its commonly available in AWS/Azure.

### PR DESCRIPTION
**Pull request by sebastian-montero**
Adds support for Elasticsearch datastores to use with the ChatGPT retrieval plug in.

closes #52

Note that because of Lucene limitations, Elasticsearch does not support vectors with dimensions > 1024. 
See: https://github.com/apache/lucene/issues/11507, https://github.com/apache/lucene/pull/874

### CODE REVIEW

**Comment by benwtrent** [comment]
Hey @sebastian-montero this is good stuff. Take a look here: https://github.com/elastic/elasticsearch/pull/95257

In 8.8, elastic will support > 1024 dims for vector storage.

**Comment by hinatades** [comment]
Elasticsearch 8.8 has been released 🎉 
https://github.com/elastic/elasticsearch/releases/tag/v8.8.0

**Comment by serenachou** [comment]
@sebastian-montero , we are eager to help where possible. Is there something you need assistance with in regards to this PR?

**Comment by sebastian-montero** [comment]
Closing this pull request as @joemcelroy from the Elastic team has created a new PR from this one and is expanding on the requirements.

**Pull request closed without merging**
