### PR TITLE
Adding Azure CosmosDB Mongo vCore as a datastore.

### PR DESCRIPTION
**Pull request by aayush3011**
## Pull Request (PR) Checklist
If you'd like to contribute, please follow the checklist below when submitting a PR. This will help us review and merge your changes faster! Thank you for contributing!

1. **Type of PR**: `[Feature]`

2. **Short Description**: I have added Azure CosmosDB MongoDB vCore as a data store. MongoDB vCore now supports vector search on embeddings, and it could be used to seamlessly integrate your AI-based applications with your data stored in the Azure CosmosDB. More details about Mongo vCore can be found here: https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search.

3. **Issue(s) Linked**: https://github.com/openai/chatgpt-retrieval-plugin/issues/380
4. **Branch**: Ensure that you have created a new branch for the changes, and it is based on the latest version of the `main` branch.

5. **Code Changes**: Make sure the code changes are minimal, focused, and relevant to the issue or feature being addressed.

6. **Commit Messages**: Write clear and concise commit messages that explain the purpose of each commit.

7. **Tests**: Include unit tests and/or integration tests for any new code or changes to existing code. Make sure all tests pass before submitting the PR.

8. **Documentation**: Update relevant documentation (e.g., README, inline comments, or external documentation) to reflect any changes made.

9. **Review Requested**: Request a review from at least one other contributor or maintainer of the repository.

10. **Video Submission** (For Complex/Large PRs): If your PR introduces significant changes, complexities, or a large number of lines of code, submit a brief video walkthrough along with the PR. The video should explain the purpose of the changes, the logic behind them, and how they address the issue or add the proposed feature. This will help reviewers to better understand your contribution and expedite the review process.

## Pull Request Naming Convention

Use the following naming convention for your PR branches:

```
<type>/<short-description>-<issue-number>
```

- `<type>`: The type of PR, such as `bugfix`, `feature`, `enhancement`, `refactor`, or `docs`. Multiple types are ok and should appear as <type>, <type2>
- `<short-description>`: A brief description of the changes made, using hyphens to separate words.
- `<issue-number>`: The issue number associated with the changes made (if applicable).

Example:

```
feature/advanced-chunking-strategy-123
```

### CODE REVIEW

**Comment by peterjdolan** [comment]
> Hey, @isafulf, @peterjdolan can you please review this PR?

I think you may have pinged the wrong Peter? I don't have any experience or expertise relevant to this change.

**Comment by aayush3011** [comment]
@pablocastro can you please review this PR?

**Comment by pablocastro** [comment]
> @pablocastro can you please review this PR?

Let me find someone in the CosmosDB team to review.

**Review by Pilchie — APPROVED** [review]
LGTM

**Comment by aayush3011** [comment]
@pablocastro can you please approve the PR as well now? Kevin doesn't have write access and one reviewer with write access is needed.

**Comment by jcodella** [comment]
@isafulf can you please help approve @aayush3011 's PR given the above?

**Comment by pablocastro** [comment]
> @pablocastro can you please approve the PR as well now? Kevin doesn't have write access and one reviewer with write access is needed.

I don't have commit access in this repo. Now that the PR is reviewed/approved, Isa or someone else in the OpenAI team will need to approve/merge.

**Comment by jcodella** [comment]
Friendly ping @isafulf, @csvoss, or @luquitared if you can help approve/merge or help us find the right folks. Thanks.

**Review by barnett-yuxiang — APPROVED** [review]

**Review by isafulf — APPROVED** [review]
Awesome!

**Pull request merged**
